name: Run My Script

on:
  workflow_dispatch:  # adds a "Run workflow" button

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # or your preferred version

    - name: Install dependencies
      run: pip install matplotlib numpy  # add more if needed

    - name: Run script
      run: python scripts/script1.py
